### ISSUE TITLE
first time payment app crash

### ISSUE THREAD

**Issue by Gagandeep1408** [payu-intrepos/PayUCheckoutPro-Flutter#27]
E/AndroidRuntime( 6996): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-55
E/AndroidRuntime( 6996): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1493)
E/AndroidRuntime( 6996): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:1109)
E/AndroidRuntime( 6996): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:281)
E/AndroidRuntime( 6996): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:464)
E/AndroidRuntime( 6996): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:217)
E/AndroidRuntime( 6996): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:117)
E/AndroidRuntime( 6996): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102)
E/AndroidRuntime( 6996): 	at com.payubiz.payu_checkoutpro_flutter.PayuCheckoutproFlutterPlugin.sendResultBack(PayuCheckoutproFlutterPlugin.kt:77)
E/AndroidRuntime( 6996): 	at com.payubiz.payu_checkoutpro_flutter.PayuCheckoutproFlutterPlugin.access$sendResultBack(PayuCheckoutproFlutterPlugin.kt:23)
E/AndroidRuntime( 6996): 	at com.payubiz.payu_checkoutpro_flutter.PayuCheckoutproFlutterPlugin$openCheckoutScreen$1$1.generateHash(PayuCheckoutproFlutterPlugin.kt:118)
E/AndroidRuntime( 6996): 	at com.payu.checkoutpro.models.x.generateSignature(SourceFile:41)
E/AndroidRuntime( 6996): 	at com.payu.india.Tasks.V2ApiTask.updateDeviceId(V2ApiTask.java:123)
E/AndroidRuntime( 6996): 	at com.payu.checkoutpro.models.f.a(SourceFile:8)
E/AndroidRuntime( 6996): 	at com.payu.checkoutpro.layers.PayUbizApiLayer.callDeviceInfoApi(SourceFile:10)
E/AndroidRuntime( 6996): 	at com.payu.ui.viewmodel.l.a(SourceFile:2428)
E/AndroidRuntime( 6996): 	at com.payu.ui.viewmodel.l.onFetchGaidResponse(SourceFile:2)
E/AndroidRuntime( 6996): 	at com.payu.checkoutpro.layers.PayUbizApiLayer$c.invoke(SourceFile:2)
E/AndroidRuntime( 6996): 	at com.payu.checkoutpro.utils.a.b(SourceFile:2)
E/AndroidRuntime( 6996): 	at com.payu.checkoutpro.utils.a$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime( 6996): 	at java.lang.Thread.run(Thread.java:1012)

**Comment by Naveen4047** [comment]
Hi team first time payment app crash any update

**Comment by shahfaizalc** [comment]
payu_checkoutpro_flutter kindly use the latest version and let us know if you face any issues
